package com.booking.service.impl;

import java.util.HashMap;
import java.util.Map;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;

import com.booking.model.Offer;
import com.stripe.Stripe;
import com.stripe.exception.APIConnectionException;
import com.stripe.exception.APIException;
import com.stripe.exception.AuthenticationException;
import com.stripe.exception.CardException;
import com.stripe.exception.InvalidRequestException;
import com.stripe.model.Charge;
import javax.annotation.PostConstruct;

/*used to create Direct charges for stripe payment gateway */
@Service
public class StripeService {

    @Value("sk_test_Lq6u3HsNgosLQJgSyHpSaN3g") //secret key is generated by stripe developer account
    String secretKey;

   
	@PostConstruct
    public void init() {
        Stripe.apiKey = secretKey;
    }

	public Charge charge(Offer chargeRequest) //this is predefined class provided from stripe used to create all parameters as per devloper need
            throws AuthenticationException, InvalidRequestException, APIConnectionException, CardException, APIException {//all parameters send to result.html
        Map<String, Object> chargeParams = new HashMap<String,Object>();
        chargeParams.put("amount", chargeRequest.getPrice());
        chargeParams.put("currency", chargeRequest.getCurrency());
        chargeParams.put("source", chargeRequest.getStripeToken());
        return Charge.create(chargeParams);
    }
}